name: PHP Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
      - uses: actions/checkout@v4
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: rwk-tlsb.net
          username: schma
          password: ${{ secrets.tlsb_ftp_password }}
          server-dir: /var/www/html/webinput/
