name: PHP Deployment
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      - name: Sync files
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: rwk-tlsb.net
          port: 22
          user: schma
          pass: ${{ secrets.tlsb_ftp_password }}
          remoteDir: '/var/www/html/webinput/'
          reverse: true        
